"""No-lookahead fill and position helpers for the Signal Probe runtime."""

from __future__ import annotations

from collections.abc import Iterable, Mapping
from dataclasses import dataclass
from datetime import datetime
from decimal import Decimal, InvalidOperation
from typing import Any

from alpha_system.runtime.probe.spec import DirectionPolicy, FillPolicy

ZERO = Decimal("0")


class SignalProbeFillError(ValueError):
    """Raised when probe fills would violate availability or no-lookahead rules."""


@dataclass(frozen=True, slots=True)
class SignalProbeObservation:
    """One local, scalar observation used by a simple signal probe."""

    event_ts: object
    available_ts: object
    label_available_ts: object
    feature_value: Decimal
    label_value: Decimal
    price: Decimal
    bid: Decimal | None = None
    ask: Decimal | None = None
    spread: Decimal | None = None
    multiplier: Decimal = Decimal("1")
    session_label: str = "RTH"
    row_id: str | None = None

    def __post_init__(self) -> None:
        _require_ts(self.event_ts, field="event_ts")
        _require_ts(self.available_ts, field="available_ts")
        _require_ts(self.label_available_ts, field="label_available_ts")
        object.__setattr__(
            self,
            "feature_value",
            _decimal(self.feature_value, field="feature_value"),
        )
        object.__setattr__(self, "label_value", _decimal(self.label_value, field="label_value"))
        object.__setattr__(self, "price", _positive_decimal(self.price, field="price"))
        object.__setattr__(self, "bid", _optional_decimal(self.bid, field="bid"))
        object.__setattr__(self, "ask", _optional_decimal(self.ask, field="ask"))
        object.__setattr__(self, "spread", _optional_decimal(self.spread, field="spread"))
        object.__setattr__(
            self,
            "multiplier",
            _positive_decimal(self.multiplier, field="multiplier"),
        )
        if self.bid is not None and self.ask is not None and self.ask < self.bid:
            raise SignalProbeFillError("ask must be greater than or equal to bid")
        object.__setattr__(
            self,
            "session_label",
            _required_text(self.session_label, field="session_label").upper(),
        )
        if self.row_id is not None:
            object.__setattr__(self, "row_id", _required_text(self.row_id, field="row_id"))

    @classmethod
    def from_mapping(cls, value: Mapping[str, Any]) -> SignalProbeObservation:
        """Build an observation from a JSON-compatible mapping."""

        return cls(
            event_ts=value.get("event_ts"),
            available_ts=value.get("available_ts"),
            label_available_ts=value.get("label_available_ts"),
            feature_value=_first_present(value, "feature_value", "signal_value", "factor_value"),
            label_value=_first_present(value, "label_value", "forward_return"),
            price=value.get("price", "1"),
            bid=value.get("bid"),
            ask=value.get("ask"),
            spread=value.get("spread"),
            multiplier=value.get("multiplier", "1"),
            session_label=str(value.get("session_label", value.get("session", "RTH"))),
            row_id=None if value.get("row_id") is None else str(value.get("row_id")),
        )

    def fill_mapping(self, *, quantity: Decimal, side: str) -> dict[str, object]:
        """Return a CostStressFill-compatible mapping for this observation."""

        payload: dict[str, object] = {
            "price": _decimal_text(self.price),
            "quantity": _decimal_text(quantity),
            "side": side,
            "multiplier": _decimal_text(self.multiplier),
            "session_label": self.session_label,
        }
        if self.bid is not None:
            payload["bid"] = _decimal_text(self.bid)
        if self.ask is not None:
            payload["ask"] = _decimal_text(self.ask)
        if self.spread is not None:
            payload["spread"] = _decimal_text(self.spread)
        return payload


@dataclass(frozen=True, slots=True)
class SignalProbeFill:
    """One scalar fill generated by the next-bar probe policy."""

    fill_index: int
    origin_signal_index: int
    position_delta: int
    side: str
    quantity: Decimal
    fill_event_ts: object
    signal_available_ts: object

    def to_cost_mapping(self, observation: SignalProbeObservation) -> dict[str, object]:
        """Return a CostStressFill-compatible mapping for runtime.cost."""

        return observation.fill_mapping(quantity=self.quantity, side=self.side)

    def to_dict(self) -> dict[str, object]:
        """Return scalar fill metadata without raw series values."""

        return {
            "fill_index": self.fill_index,
            "origin_signal_index": self.origin_signal_index,
            "position_delta": self.position_delta,
            "side": self.side,
            "quantity": _decimal_text(self.quantity),
            "same_bar_fill": self.fill_index == self.origin_signal_index,
        }


@dataclass(frozen=True, slots=True)
class SignalProbePositionSeries:
    """Scalar summary of next-bar positions for one threshold."""

    threshold: Decimal
    positions: tuple[int, ...]
    origin_signal_indices: tuple[int | None, ...]
    fills: tuple[SignalProbeFill, ...]
    gross_pnl_proxy_by_bar: tuple[Decimal, ...]
    turnover: Decimal
    trade_count: int
    gross_total_proxy: Decimal
    gross_expectancy_proxy: Decimal | None
    drawdown_proxy: Decimal
    observation_count: int

    @property
    def cost_fill_mappings(self) -> tuple[dict[str, object], ...]:
        """Cost mappings are built by ``to_cost_fill_mappings`` with observations."""

        raise SignalProbeFillError("call to_cost_fill_mappings(observations) instead")

    def to_cost_fill_mappings(
        self,
        observations: Iterable[SignalProbeObservation],
    ) -> tuple[dict[str, object], ...]:
        """Return CostStressFill-compatible mappings for runtime.cost."""

        rows = tuple(observations)
        return tuple(fill.to_cost_mapping(rows[fill.fill_index]) for fill in self.fills)

    def to_summary(self) -> dict[str, object]:
        """Return scalar position and trade summary fields."""

        return {
            "threshold": _decimal_text(self.threshold),
            "observation_count": self.observation_count,
            "trade_count": self.trade_count,
            "turnover": _decimal_text(self.turnover),
            "gross_total_proxy": _decimal_text(self.gross_total_proxy),
            "gross_expectancy_proxy": (
                None
                if self.gross_expectancy_proxy is None
                else _decimal_text(self.gross_expectancy_proxy)
            ),
            "drawdown_proxy": _decimal_text(self.drawdown_proxy),
            "same_bar_fill_count": sum(
                1 for fill in self.fills if fill.fill_index == fill.origin_signal_index
            ),
        }


def build_next_bar_position_series(
    observations: Iterable[SignalProbeObservation | Mapping[str, Any]],
    *,
    threshold: Decimal | int | float | str,
    direction_policy: DirectionPolicy | str,
    fill_policy: FillPolicy,
) -> SignalProbePositionSeries:
    """Convert a thresholded signal into positions using delayed eligible fills.

    The desired position generated at observation ``i`` can first become active
    at ``i + fill_policy.delay_bars``. A signal whose ``available_ts`` is later
    than the fill bar ``event_ts`` fails closed.
    """

    active_threshold = _positive_decimal(threshold, field="threshold")
    active_policy = _coerce_direction(direction_policy)
    if not isinstance(fill_policy, FillPolicy):
        raise SignalProbeFillError("fill_policy must be a FillPolicy")

    rows = tuple(_coerce_observation(row) for row in observations)
    _validate_event_order(rows)
    desired = tuple(
        _desired_position(row.feature_value, threshold=active_threshold, policy=active_policy)
        for row in rows
    )

    positions: list[int] = []
    origin_indices: list[int | None] = []
    active_position = 0
    for index, row in enumerate(rows):
        origin_index = index - fill_policy.delay_bars
        if origin_index >= 0:
            origin = rows[origin_index]
            if _ts_key(origin.available_ts) > _ts_key(row.event_ts):
                raise SignalProbeFillError(
                    "signal available_ts must not be later than the eligible fill bar event_ts"
                )
            active_position = desired[origin_index]
            origin_indices.append(origin_index)
        else:
            origin_indices.append(None)
        positions.append(active_position)

    fills: list[SignalProbeFill] = []
    gross_by_bar: list[Decimal] = []
    turnover = ZERO
    previous_position = 0
    for index, (row, position, origin_index) in enumerate(zip(rows, positions, origin_indices)):
        delta = position - previous_position
        if delta != 0:
            side = "buy" if delta > 0 else "sell"
            quantity = Decimal(abs(delta))
            origin = rows[origin_index] if origin_index is not None else row
            turnover += quantity
            fills.append(
                SignalProbeFill(
                    fill_index=index,
                    origin_signal_index=-1 if origin_index is None else origin_index,
                    position_delta=delta,
                    side=side,
                    quantity=quantity,
                    fill_event_ts=row.event_ts,
                    signal_available_ts=origin.available_ts,
                )
            )
        gross_by_bar.append(Decimal(position) * row.label_value)
        previous_position = position

    gross_total = sum(gross_by_bar, ZERO)
    trade_count = len(fills)
    expectancy = None if trade_count == 0 else gross_total / Decimal(trade_count)
    return SignalProbePositionSeries(
        threshold=active_threshold,
        positions=tuple(positions),
        origin_signal_indices=tuple(origin_indices),
        fills=tuple(fills),
        gross_pnl_proxy_by_bar=tuple(gross_by_bar),
        turnover=turnover,
        trade_count=trade_count,
        gross_total_proxy=gross_total,
        gross_expectancy_proxy=expectancy,
        drawdown_proxy=_max_drawdown(gross_by_bar),
        observation_count=len(rows),
    )


def _coerce_observation(
    value: SignalProbeObservation | Mapping[str, Any],
) -> SignalProbeObservation:
    if isinstance(value, SignalProbeObservation):
        return value
    if isinstance(value, Mapping):
        return SignalProbeObservation.from_mapping(value)
    raise SignalProbeFillError("probe observations must be mappings or SignalProbeObservation")


def _validate_event_order(rows: tuple[SignalProbeObservation, ...]) -> None:
    previous: tuple[int, object] | None = None
    for index, row in enumerate(rows):
        current = _ts_key(row.event_ts)
        if previous is not None and current <= previous:
            raise SignalProbeFillError("probe observations must have strictly increasing event_ts")
        previous = current
        if _ts_key(row.available_ts) < current:
            continue
        if _ts_key(row.available_ts) == current:
            continue
        # Availability after the event can still be valid if the explicit fill delay
        # waits long enough; the fill loop checks that against the eligible fill bar.
        if index == len(rows) - 1:
            continue


def _desired_position(
    feature_value: Decimal,
    *,
    threshold: Decimal,
    policy: DirectionPolicy,
) -> int:
    if policy is DirectionPolicy.LONG_SHORT_FLAT:
        if feature_value >= threshold:
            return 1
        if feature_value <= -threshold:
            return -1
        return 0
    if policy is DirectionPolicy.LONG_FLAT:
        return 1 if feature_value >= threshold else 0
    if policy is DirectionPolicy.SHORT_FLAT:
        return -1 if feature_value <= -threshold else 0
    raise SignalProbeFillError(f"unsupported direction policy: {policy}")


def _max_drawdown(values: Iterable[Decimal]) -> Decimal:
    peak = ZERO
    cumulative = ZERO
    max_drawdown = ZERO
    for value in values:
        cumulative += value
        if cumulative > peak:
            peak = cumulative
        drawdown = peak - cumulative
        if drawdown > max_drawdown:
            max_drawdown = drawdown
    return max_drawdown


def _coerce_direction(value: DirectionPolicy | str) -> DirectionPolicy:
    if isinstance(value, DirectionPolicy):
        return value
    if isinstance(value, str):
        try:
            return DirectionPolicy(value)
        except ValueError as exc:
            raise SignalProbeFillError(f"unsupported direction_policy: {value}") from exc
    raise SignalProbeFillError("direction_policy must be DirectionPolicy or str")


def _first_present(value: Mapping[str, Any], *keys: str) -> object:
    for key in keys:
        if key in value:
            return value[key]
    raise SignalProbeFillError(f"observation is missing one of: {', '.join(keys)}")


def _required_text(value: object, *, field: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise SignalProbeFillError(f"{field} is required")
    return value.strip()


def _require_ts(value: object, *, field: str) -> None:
    if value is None or (isinstance(value, str) and not value.strip()):
        raise SignalProbeFillError(f"{field} is required")
    _ts_key(value)


def _ts_key(value: object) -> tuple[int, object]:
    if isinstance(value, datetime):
        return (0, value.timestamp())
    if isinstance(value, int | float) and not isinstance(value, bool):
        return (0, float(value))
    if isinstance(value, str):
        text = value.strip()
        if not text:
            raise SignalProbeFillError("timestamp strings must not be empty")
        try:
            normalized = text.replace("Z", "+00:00")
            return (0, datetime.fromisoformat(normalized).timestamp())
        except ValueError:
            return (1, text)
    raise SignalProbeFillError(f"unsupported timestamp type: {type(value).__name__}")


def _decimal(value: object, *, field: str) -> Decimal:
    if isinstance(value, bool) or value is None:
        raise SignalProbeFillError(f"{field} must be numeric")
    try:
        active = value if isinstance(value, Decimal) else Decimal(str(value))
    except (InvalidOperation, ValueError) as exc:
        raise SignalProbeFillError(f"{field} must be numeric") from exc
    if not active.is_finite():
        raise SignalProbeFillError(f"{field} must be finite")
    return active


def _optional_decimal(value: object, *, field: str) -> Decimal | None:
    if value is None:
        return None
    return _decimal(value, field=field)


def _positive_decimal(value: object, *, field: str) -> Decimal:
    active = _decimal(value, field=field)
    if active <= ZERO:
        raise SignalProbeFillError(f"{field} must be positive")
    return active


def _decimal_text(value: Decimal) -> str:
    return format(value.normalize(), "f")


__all__ = [
    "SignalProbeFill",
    "SignalProbeFillError",
    "SignalProbeObservation",
    "SignalProbePositionSeries",
    "build_next_bar_position_series",
]
